POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "accountNumber": "E330G8",
    "pin": "1232"
}

###
POST http://localhost:5000/api/auth/signup
Content-Type: application/json

{
    "name": "Hari",
    "pin": "1232",
    "accountType": "Savings",
    "balance": 1222
}

###
GET http://localhost:4000/api/account/getBalance
Content-Type: application/json

{
    "accountNumber": "E330G8"
}

###
# Get Balance using the Access Token
GET http://localhost:4000/api/account/getBalance
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50TnVtYmVyIjoiRTMzMEc4IiwiaWF0IjoxNzU0NTA3ODMxLCJleHAiOjE3NTQ1MDc4ODF9.5k2AD2vhC5i4ioUQel0DqfOq7vIErc-jY7MABVepskA
Content-Type: application/json

{
    "accountNumber": "E330G8"
}

###
# Takes the refreshToken and checks in the refreshToken Array If yes then creates a new Access Token
POST http://localhost:5000/api/auth/token
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50TnVtYmVyIjoiRTMzMEc4IiwiaWF0IjoxNzU0NTA3ODMxfQ.vZD7SY8m_MXWFQ2QyHycv4JTwDP45c-noStNKxJbPQI"
}

###
# Takes refreshToken and removes it from the refreshToken Array ( User cannot regenerate access token i.e. Logout )
DELETE http://localhost:5000/api/auth/logout
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50TnVtYmVyIjoiRTMzMEc4IiwiaWF0IjoxNzU0NTA3ODMxfQ.vZD7SY8m_MXWFQ2QyHycv4JTwDP45c-noStNKxJbPQI"
}

###
# Generate new access and refresh token
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "accountNumber": "E330G8",
    "pin": "1232"
}

###
# Takes Access Token and adds amount (" DEPOSIT ")
POST http://localhost:4000/api/account/deposit
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50TnVtYmVyIjoiRTMzMEc4IiwiaWF0IjoxNzU0NTExNjMyLCJleHAiOjE3NTQ1MTE2ODJ9._JSXmmM9bON-AQ1HgTw0HPK_YWNNUsoQJgy34hw1gXU
Content-Type: application/json

{
    "accountNumber": "E330G8",
    "amount": 200
}

###
# Takes Access Token and reduce amount (" WITHDRAW ")
POST http://localhost:4000/api/account/withdraw
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50TnVtYmVyIjoiRTMzMEc4IiwiaWF0IjoxNzU0NTEyNzI5LCJleHAiOjE3NTQ1MTI3Nzl9.TCk-cWdEUTCWpZjgU8LjX54eNE9M8eYMCyE8Tj4ykzg
Content-Type: application/json

{
    "accountNumber": "E330G8",
    "amount": 200
}

###
# Takes Access Token and fetch mini statement (" TRANSACTIONS ")
GET http://localhost:4000/api/account/transactions
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50TnVtYmVyIjoiRTMzMEc4IiwiaWF0IjoxNzU0NTE0MDgxLCJleHAiOjE3NTQ1MTQxMzF9.q3TwekVbpWKRLfTwyiFkchRFzLr0zuaB7symNOL6bIQ
Content-Type: application/json

{
    "accountNumber": "E330G8"
}