###
POST http://localhost:5000/api/auth/signup
Content-Type: application/json

{
    "name": "Lee",
    "pin": "1111",
    "accountType": "Savings",
    "balance": 1000
}

###
# Get Balance using the Access Token
GET http://localhost:4000/api/account/getBalance
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50TnVtYmVyIjoiMEkzQklFIiwiaWF0IjoxNzU0NjcyMTU4LCJleHAiOjE3NTQ2NzU3NTh9.blLd_HS_2ns2TW473Ndwj__E43Sz4shaN1JjxZAzQlg
Content-Type: application/json

{
    "accountNumber": "E330G8"
}

###
# Takes the refreshToken and checks in the refreshToken Array If yes then creates a new Access Token
POST http://localhost:5000/api/auth/token
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50TnVtYmVyIjoiRTMzMEc4IiwiaWF0IjoxNzU0NTA3ODMxfQ.vZD7SY8m_MXWFQ2QyHycv4JTwDP45c-noStNKxJbPQI"
}

###
# Takes refreshToken and removes it from the refreshToken Array ( User cannot regenerate access token i.e. Logout )
DELETE http://localhost:5000/api/auth/logout
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50TnVtYmVyIjoiRTMzMEc4IiwiaWF0IjoxNzU0NTA3ODMxfQ.vZD7SY8m_MXWFQ2QyHycv4JTwDP45c-noStNKxJbPQI"
}

###
# Generate new access and refresh token
POST http://localhost:5000/api/auth/login
Content-Type: application/json

# Hari Credintials
{
    "accountNumber": "E330G8",
    "pin": "1111"
}

# Lee Credintials
# {
#     "accountNumber": "0I3BIE",
#     "pin": "1111"
# }

###
# Takes Access Token and adds amount (" DEPOSIT ")
POST http://localhost:4000/api/account/deposit
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50TnVtYmVyIjoiRTMzMEc4IiwiaWF0IjoxNzU0NTExNjMyLCJleHAiOjE3NTQ1MTE2ODJ9._JSXmmM9bON-AQ1HgTw0HPK_YWNNUsoQJgy34hw1gXU
Content-Type: application/json

{
    "accountNumber": "E330G8",
    "amount": 200
}

###
# Takes Access Token and reduce amount (" WITHDRAW ")
POST http://localhost:4000/api/account/withdraw
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50TnVtYmVyIjoiRTMzMEc4IiwiaWF0IjoxNzU0NTEyNzI5LCJleHAiOjE3NTQ1MTI3Nzl9.TCk-cWdEUTCWpZjgU8LjX54eNE9M8eYMCyE8Tj4ykzg
Content-Type: application/json

{
    "accountNumber": "E330G8",
    "amount": 200
}

###
# Takes Access Token and fetch mini statement (" TRANSACTIONS ")
GET http://localhost:4000/api/account/transactions
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50TnVtYmVyIjoiRTMzMEc4IiwiaWF0IjoxNzU0NjcxOTM1LCJleHAiOjE3NTQ2NzU1MzV9.jLg9YC810LixJ-pS9v4KRqBazCxkOItb7vqAKUhLs24
Content-Type: application/json

{
    "accountNumber": "E330G8"
}

###
# Takes Access Token and fetch mini statement (" TRANSACTIONS ")
POST http://localhost:4000/api/account/change-pin
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50TnVtYmVyIjoiRTMzMEc4IiwiaWF0IjoxNzU0NjcxOTM1LCJleHAiOjE3NTQ2NzU1MzV9.jLg9YC810LixJ-pS9v4KRqBazCxkOItb7vqAKUhLs24
Content-Type: application/json

{
    "pin": "1311",
    "newPin": "1111"
}

###
POST http://localhost:4000/api/account/transfer
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50TnVtYmVyIjoiRTMzMEc4IiwiaWF0IjoxNzU0NjcyMzE4LCJleHAiOjE3NTQ2NzU5MTh9.mHSqliEyNKrs9nXJgHWRb29vhqCRvJV7LOuLFOYKIK0
Content-Type: application/json

{
    "reciverAccountNumber": "0I3BIE",
    "amount": 200
}