POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "accountNumber": "E330G8",
    "pin": "1232"
}

###
POST http://localhost:5000/api/auth/signup
Content-Type: application/json

{
    "name": "Hari",
    "pin": "1232",
    "accountType": "Savings",
    "balance": 1222
}